backend:
  name: git-gateway
  branch: main

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'products'
    label: 'Товары'
    folder: 'content/products'
    fields:
      [
        { label: 'Название', name: 'title', widget: 'string' },
        { label: 'Цена', name: 'price', widget: 'number' },
      ]
